use "/Users/gustavomurillovelazquez/Documents/GitHub/ppol768-spring23/Class Materials/week-04/03_assignment/01_data/q4_Tz_student_roster_html.dta", clear

gen subject_position = strpos(s, "SUBJECT")

replace s = substr(s, 3852, .)


split s, parse("</TD></TR>")

gen serial = _n
drop s
reshape long s, i(serial) j(j)

exit

substr("abcdef",2,3) = "bcd"


<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0001</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20150348195</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">M</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>DANIEL JAMES KAGUO</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - B, English - A, Maarifa - C, Hisabati - C, Science - B, Uraia - C, Average Grade - B</FONT></TD></TR>
<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0002</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20156273910</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">M</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>DAVIS ROBERT LUCAS</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - A, English - A, Maarifa - C, Hisabati - B, Science - B, Uraia - B, Average Grade - B</FONT></TD></TR>
<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0003</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20150348196</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">M</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>ELISANTE GABRIEL NKYA</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - A, English - A, Maarifa - D, Hisabati - B, Science - B, Uraia - C, Average Grade - B</FONT></TD></TR>
<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0004</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20156555361</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">M</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>FESTUS RENASTUS CHIMOLA</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - B, English - A, Maarifa - C, Hisabati - B, Science - B, Uraia - C, Average Grade - B</FONT></TD></TR>
<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0005</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20156272958</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">M</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>IAN INNOCENT GEOFREY</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - A, English - A, Maarifa - C, Hisabati - A, Science - C, Uraia - B, Average Grade - B</FONT></TD></TR>
<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0006</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20150316147</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">M</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>MESHACK THOMAS NATHANAEL</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - B, English - B, Maarifa - C, Hisabati - B, Science - B, Uraia - C, Average Grade - B</FONT></TD></TR>
<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0007</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20150348198</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">M</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>PHILIPO AYUBU MBWANA</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - B, English - B, Maarifa - D, Hisabati - B, Science - B, Uraia - C, Average Grade - B</FONT></TD></TR>
<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0008</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20150348199</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">M</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>SALIM IDDY RASHID</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - A, English - A, Maarifa - B, Hisabati - B, Science - B, Uraia - C, Average Grade - B</FONT></TD></TR>
<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0009</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20150377806</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">F</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>DORA SALVATORY THADEI</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - B, English - A, Maarifa - C, Hisabati - A, Science - B, Uraia - B, Average Grade - B</FONT></TD></TR>
<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0010</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20152878842</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">F</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>EVALYNE PERFECT ELIAS</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - A, English - A, Maarifa - B, Hisabati - B, Science - B, Uraia - C, Average Grade - B</FONT></TD></TR>
<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0011</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20150348200</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">F</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>FATUMA SALIM SAIDI</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - A, English - A, Maarifa - C, Hisabati - A, Science - B, Uraia - C, Average Grade - B</FONT></TD></TR>
<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0012</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20150348201</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">F</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>HAPPY JULIUS MZIRAI</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - B, English - A, Maarifa - C, Hisabati - D, Science - B, Uraia - B, Average Grade - B</FONT></TD></TR>
<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0013</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20150348202</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">F</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>JOAN MANASE GEOFREY</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - A, English - A, Maarifa - B, Hisabati - A, Science - A, Uraia - B, Average Grade - A</FONT></TD></TR>
<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0014</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20150348203</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">F</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>JOAN WILHARD MWANGA</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - A, English - A, Maarifa - C, Hisabati - A, Science - A, Uraia - B, Average Grade - A</FONT></TD></TR>
<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0015</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20150348204</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">F</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>SOPHIA HAKEEM PALLANGYO</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - B, English - A, Maarifa - C, Hisabati - A, Science - A, Uraia - C, Average Grade - B</FONT></TD></TR>
<TR><TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">PS0101114-0016</FONT></TD>
<TD WIDTH="10%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">20150348205</FONT></TD>
<TD WIDTH="5%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="CENTER">F</FONT></TD>
 <TD WIDTH="25%" VALIGN="LEFT">
<FONT FACE="Arial" SIZE=1><P>ZAINAB RASHIDI SALUM</FONT></TD>
<TD WIDTH="55%" VALIGN="MIDDLE">
<FONT FACE="Arial" SIZE=1><P ALIGN="LEFT">Kiswahili - B, English - A, Maarifa - D, Hisabati - A, Science - B, Uraia - B, Average Grade - B</FONT></TD></TR>
</TABLE>
</BODY>
